name: Hello World
'on':
  workflow_dispatch: null
  pull_request: null
  pull_request_target: null
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
    - if: github.event_name == 'pull_request_target'
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/head
        persist-credentials: false
    - if: github.event_name != 'pull_request_target'
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Say hello
      run: "echo \"Hello World, I\u2019m hiding [${{ secrets.password }}]!\""
    - name: Execute script
      run: chmod 755 ./foo.sh && ./foo.sh
