name: Triggered Workflow
'on':
  workflow_run:
    workflows:
    - Hello World
    types:
    - completed
jobs:
  triggered-job1-parallel:
    runs-on: ubuntu-latest
    steps:
    - name: Job1 Triggered
      run: 'sleep 30s

        echo "I''ve been triggered by ${{ github.event.workflow_run.name }}!"

        echo "Secret: [${{ secrets.password }}]"

        '
  triggered-job2-parallel:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Job2 Triggered
      run: 'sleep 30s

        echo "I''ve been triggered by ${{ github.event.workflow_run.name }}!"

        echo "Secret: [${{ secrets. password }}]"

        '
  triggered-matrix-of-jobs-sequential:
    runs-on: ubuntu-latest
    needs: triggered-job2-parallel
    strategy:
      fail-fast: false
      matrix:
        kube-runtime:
        - K3s-1.19
        - MicroK8s-1.19
        - Kubernetes-1.19
    steps:
    - name: ${{ matrix.kube-runtime }} Triggered
      run: 'echo "${{ matrix.kube-runtime }} triggered by ${{ github.event.workflow_run.name
        }} !"

        echo "Secret: [${{ secrets. password }}]"

        '
